# Generated by Django 2.2 on 2019-04-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=30)),
                ('specie', models.SmallIntegerField(choices=[(0, 'Caine'), (1, 'Pisica')])),
                ('luna', models.SmallIntegerField()),
                ('anul', models.SmallIntegerField()),
                ('sex', models.SmallIntegerField(choices=[(0, 'Masculin'), (1, 'Feminin')])),
                ('talie', models.SmallIntegerField(choices=[(0, 'Mic'), (1, 'Mediu'), (2, 'Mare')])),
                ('observatie', models.TextField()),
                ('este_adoptat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrijitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=60)),
                ('nr_telefon', models.CharField(max_length=10)),
                ('este_voluntar', models.BooleanField()),
                ('data_angajarii', models.DateField()),
                ('este_angajat', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezerva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.SmallIntegerField()),
                ('dimensiune', models.SmallIntegerField(choices=[(0, 'Mic'), (1, 'Mediu'), (2, 'Mare')])),
                ('observatii', models.TextField()),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adapost.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Eveniment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adapost.Animal')),
                ('ingrijitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adapost.Ingrijitor')),
            ],
        ),
    ]
