# Generated by Django 2.2 on 2019-04-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adapost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name_plural': 'Animale'},
        ),
        migrations.AlterModelOptions(
            name='eveniment',
            options={'verbose_name_plural': 'Evenimente'},
        ),
        migrations.AlterModelOptions(
            name='ingrijitor',
            options={'verbose_name_plural': 'Ingrijitori'},
        ),
        migrations.AlterModelOptions(
            name='rezerva',
            options={'verbose_name_plural': 'Rezerve'},
        ),
        migrations.RemoveField(
            model_name='eveniment',
            name='animal',
        ),
        migrations.AddField(
            model_name='eveniment',
            name='rezerva',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='adapost.Rezerva'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingrijitor',
            name='este_angajat',
            field=models.BooleanField(help_text='Marcheaza daca ingrijitorul este activ in companie'),
        ),
        migrations.AlterField(
            model_name='ingrijitor',
            name='nr_telefon',
            field=models.CharField(max_length=10, verbose_name='numar telefon'),
        ),
    ]
